# -----------------------------------------------------------------------------
# Stage 1: Builder — install deps, generate Prisma client, compile NestJS
# -----------------------------------------------------------------------------
FROM node:20-alpine AS builder

# OpenSSL for Prisma engine (Alpine uses OpenSSL 3.x; binaryTarget linux-musl-openssl-3.0.x)
RUN apk add --no-cache openssl

WORKDIR /app

# Copy Prisma schema before npm ci (postinstall runs "prisma generate" and needs the schema)
COPY prisma ./prisma/
COPY package.json package-lock.json ./
RUN npm ci

# Prisma client generated by postinstall above; explicit step for clarity
RUN npx prisma generate

# Copy source and build the app (dist/ is the only artifact we need in the final image)
COPY . .
RUN npm run build

# -----------------------------------------------------------------------------
# Stage 2: Runner — minimal runtime image, no devDependencies or source
# Uses Alpine Linux; builds identically on Windows, macOS, or Linux hosts.
# -----------------------------------------------------------------------------
FROM node:20-alpine AS runner

# Production mode: disables dev checks and can improve performance
ENV NODE_ENV=production

# Prisma on Alpine needs OpenSSL at runtime; OpenSSL 3.x matches binaryTarget linux-musl-openssl-3.0.x
RUN apk add --no-cache openssl

WORKDIR /app

# Copy Prisma schema before npm ci so postinstall (prisma generate) can run
COPY prisma ./prisma/

# Copy dependency manifests and install production deps (postinstall runs prisma generate)
COPY package.json package-lock.json ./
RUN npm ci --omit=dev

# Copy compiled app from builder (no TypeScript or Nest CLI in this stage)
COPY --from=builder /app/dist ./dist

# Run as non-root user for better security (container escape / file system)
# Alpine: addgroup/adduser; same image regardless of host OS
RUN addgroup -g 1001 -S nodejs && \
    adduser -S nestjs -u 1001 -G nodejs && \
    chown -R nestjs:nodejs /app
USER nestjs

EXPOSE 3000

# NestJS outputs to dist/src/main.js when preserving src/ structure
CMD ["node", "dist/src/main.js"]
